apiVersion: v1
kind: Service
metadata:
  name: externalname-svc
  namespace: session11
spec:
  # ExternalName does NOT proxy traffic and has no selector, no ClusterIP
  # and no endpoints. CoreDNS simply returns a CNAME to externalName.
  type: ExternalName
  externalName: www.google.com
