apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-running
  namespace: session10
  labels:
    phase-demo: running
spec:
  containers:
    - name: web
      image: nginx:1.24-alpine
      ports:
        - containerPort: 80
